import type { Config } from 'tailwindcss'

const config: {
  plugins: any[]
  theme: {
    extend: {
      colors: {
        'neutral-low-300': string
        'blue-high-200': string
        'blue-low-800': string
        'green-low-500': string
        'blue-high-600': string
        'blue-low-400': string
        'green-low-900': string
        'orange-low-900': string
        'neutral-low-700': string
        'god-black': string
        'blue-high-0': string
        'yellow-850': string
        'brown-200': string
        'button-tracking-hover-secondary-tonal': string
        'brown-600': string
        'green-low-100': string
        'object-secondary': string
        'green-high-500': string
        'object-primary': string
        'green-high-100': string
        'orange-high-400': string
        'neutral-high-700': string
        'orange-high-800': string
        'orange-high-0': string
        'green-high-900': string
        'neutral-high-300': string
        'button-content-white': string
        'god-white': string
        'yellow-200': string
        'green-high-0': string
        'orange-low-500': string
        primary: string
        'yellow-600': string
        'orange-low-100': string
        'neutral-low-400': string
        'green-low-400': string
        'blue-high-100': string
        'blue-low-900': string
        'green-low-800': string
        'blue-high-500': string
        'blue-low-500': string
        'background-caution': string
        'object-high-emphasis': string
        'blue-low-100': string
        'neutral-low-800': string
        'button-content-black': string
        'yellow-150': string
        'button-tracking-hover-neutral': string
        'yellow-950': string
        'brown-100': string
        'brown-500': string
        'brown-900': string
        'green-high-600': string
        'orange-high-100': string
        'green-high-200': string
        'orange-high-500': string
        'neutral-high-600': string
        'orange-high-900': string
        'background-success': string
        'blue-low-0': string
        'neutral-high-200': string
        'yellow-300': string
        'orange-low-600': string
        'blue-high-900': string
        'button-tracking-hover-primary-tonal': string
        'yellow-700': string
        'orange-low-200': string
        'neutral-low-0': string
        'button-content-success': string
        'green-low-300': string
        'neutral-low-500': string
        'button-tracking-primary': string
        'object-low-emphasis': string
        'blue-low-600': string
        'green-low-700': string
        'neutral-low-100': string
        'blue-high-400': string
        'blue-low-200': string
        'button-tracking-primary-tonal': string
        'neutral-low-900': string
        'background-Surface-00': string
        'button-content-caution': string
        'background-primary-light': string
        'object-caution': string
        'background-scrim': string
        'orange-low-950': string
        'brown-400': string
        'green-high-700': string
        'brown-800': string
        'yellow-0': string
        'background-secondary': string
        'green-high-300': string
        'orange-low-50': string
        'brown-0': string
        'orange-high-200': string
        'orange-high-600': string
        'neutral-high-500': string
        'button-tracking-secondary-tonal': string
        'object-primary-low': string
        'neutral-high-900': string
        'button-tracking-secondary': string
        'neutral-high-100': string
        'yellow-400': string
        'orange-low-700': string
        'button-tracking-neutral': string
        'object-success': string
        'blue-high-800': string
        'yellow-800': string
        'orange-low-300': string
        'button-tracking-black': string
        'blue-high-300': string
        'green-low-0': string
        'neutral-low-600': string
        'yellow-900': string
        'green-low-600': string
        'blue-high-700': string
        'blue-low-700': string
        'neutral-low-200': string
        'orange-low-800': string
        'blue-low-300': string
        'button-tracking-hover-primary': string
        'neutral-high-0': string
        'god-primary': string
        'brown-300': string
        'button-tracking-hover-secondary': string
        'green-low-200': string
        'brown-700': string
        'orange-low-0': string
        'button-content-primary': string
        'green-high-800': string
        'green-high-400': string
        'orange-high-300': string
        'neutral-high-800': string
        'button-tracking-hover-black': string
        'blue-low-550': string
        'orange-high-700': string
        'background-Surface-03': string
        'background-Surface-02': string
        'background-Surface-01': string
        'object-white': string
        'background-primary': string
        'neutral-high-400': string
        'border-outline-2': string
        'border-outline-1': string
        'yellow-100': string
        'orange-low-400': string
        'border-grade-1': string
        'border-grade-2': string
        'button-content-secondary': string
        'yellow-500': string
      }
    }
  }
  corePlugins: {
    aspectRatio: boolean
  }
  content: string[]
} = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#28387E',

        // Reference
        // Neutral
        'neutral-low-0': '#FFFFFF',
        'neutral-low-100': '#FAFAFA',
        'neutral-low-200': '#F5F5F5',
        'neutral-low-300': '#F0F0F0',
        'neutral-low-400': '#EBEBEB',
        'neutral-low-500': '#E6E6E6',
        'neutral-low-600': '#E0E0E0',
        'neutral-low-700': '#DBDBDB',
        'neutral-low-800': '#D6D6D6',
        'neutral-low-900': '#D1D1D1',
        'neutral-high-0': '#B8B8B8',
        'neutral-high-100': '#A3A3A3',
        'neutral-high-200': '#8F8F8F',
        'neutral-high-300': '#7A7A7A',
        'neutral-high-400': '#666666',
        'neutral-high-500': '#525252',
        'neutral-high-600': '#3D3D3D',
        'neutral-high-700': '#2A2A2A',
        'neutral-high-800': '#151515',
        'neutral-high-900': '#000000',
        // Blue
        'blue-high-0': '#142E81',
        'blue-high-100': '#142E81',
        'blue-high-200': '#13318A',
        'blue-high-300': '#152F7D',
        'blue-high-400': '#172D70',
        'blue-high-500': '#172A63',
        'blue-high-600': '#172756',
        'blue-high-700': '#16234A',
        'blue-high-800': '#141E3D',
        'blue-high-900': '#111930',
        'blue-low-0': '#E6EAF5',
        'blue-low-100': '#E6EAF5',
        'blue-low-200': '#A9B6DE',
        'blue-low-300': '#A9B6DE',
        'blue-low-400': '#7488C7',
        'blue-low-500': '#7488C7',
        'blue-low-550': '#5361A0',
        'blue-low-600': '#4760B0',
        'blue-low-700': '#4760B0',
        'blue-low-800': '#223F99',
        'blue-low-900': '#223F99',
        // Brown
        'brown-0': '#997712',
        'brown-100': '#8C6D0F',
        'brown-200': '#7F630D',
        'brown-300': '#73590A',
        'brown-400': '#664F08',
        'brown-500': '#594406',
        'brown-600': '#4C3A05',
        'brown-700': '#403103',
        'brown-800': '#332702',
        'brown-900': '#261D01',
        // Yellow
        'yellow-0': '#FEFBF4',
        'yellow-100': '#F7EED4',
        'yellow-150': '#FFF5DB',
        'yellow-200': '#F0E2B8',
        'yellow-300': '#E8D499',
        'yellow-400': '#E0C77E',
        'yellow-500': '#D9BC64',
        'yellow-600': '#D1AF4B',
        'yellow-700': '#C9A434',
        'yellow-800': '#C2991F',
        'yellow-850': '#FFC10E',
        'yellow-900': '#FFC30F',
        'yellow-950': '#F39200',
        // Green
        'green-high-0': '#14960F',
        'green-high-100': '#118A0C',
        'green-high-200': '#0E7D0A',
        'green-high-300': '#0B7008',
        'green-high-400': '#096306',
        'green-high-500': '#075704',
        'green-high-600': '#054A03',
        'green-high-700': '#043D02',
        'green-high-800': '#033201',
        'green-high-900': '#022401',
        'green-low-0': '#EDFDED',
        'green-low-100': '#C2EDC0',
        'green-low-200': '#A4E1A2',
        'green-low-300': '#88D485',
        'green-low-400': '#6FC76B',
        'green-low-500': '#58BA54',
        'green-low-600': '#43AD3E',
        'green-low-700': '#30A12B',
        'green-low-800': '#1F941B',
        'green-low-900': '#10870C',
        // Orange
        'orange-high-0': '#BF4B11',
        'orange-high-100': '#AF430D',
        'orange-high-200': '#A13D0B',
        'orange-high-300': '#913608',
        'orange-high-400': '#822F06',
        'orange-high-500': '#732904',
        'orange-high-600': '#632303',
        'orange-high-700': '#541D02',
        'orange-high-800': '#451801',
        'orange-high-900': '#361200',
        'orange-low-0': '#FFF3ED',
        'orange-low-50': '#FFF4ED',
        'orange-low-100': '#FCE0D2',
        'orange-low-200': '#FACFB9',
        'orange-low-300': '#F7BDA0',
        'orange-low-400': '#F5AC88',
        'orange-low-500': '#F29C71',
        'orange-low-600': '#F08D5B',
        'orange-low-700': '#ED7D45',
        'orange-low-800': '#EB6E2F',
        'orange-low-900': '#E85F1A',
        'orange-low-950': '#BF4E11',

        // Kit
        // God
        'god-primary': '#223F99',
        'god-white': '#FFFFFF',
        'god-black': '#000000',
        // Background
        'background-Surface-00': '#FFFFFF',
        'background-Surface-01': '#FAFAFA',
        'background-Surface-02': '#F5F5F5',
        'background-Surface-03': '#F0F0F0',
        'background-primary': '#E6EAF5',
        'background-primary-light': '#F2F5FF',
        'background-secondary': '#FFF5DB',
        'background-success': '#EDFDED',
        'background-caution': '#FFF4ED',
        'background-scrim': '#666666',
        // Object
        'object-white': '#FFFFFF',
        'object-high-emphasis': '#000000',
        'object-low-emphasis': '#666666',
        'object-primary': '#233F98',
        'object-primary-low': '#7488C7',
        'object-secondary': '#FFC10E',
        'object-success': '#10870C',
        'object-caution': '#BF4E11',
        // Borders
        'border-grade-1': '#F0F0F0',
        'border-grade-2': '#E6E6E6',
        'border-outline-1': '#C8C8C8',
        'border-outline-2': '#BFBFBF',
        // Button Content
        'button-content-white': '#FFFFFF',
        'button-content-black': '#000000',
        'button-content-primary': '#223F99',
        'button-content-secondary': '#FFC10E',
        'button-content-success': '#14960F',
        'button-content-caution': '#BF4E11',
        // Button Tracking
        'button-tracking-neutral': '#EBEBEB',
        'button-tracking-black': '#2A2A2A',
        'button-tracking-primary': '#223F99',
        'button-tracking-primary-tonal': '#E6EAF5',
        'button-tracking-secondary': '#FFC10E',
        'button-tracking-secondary-tonal': '#FFF5DB',
        // Button Tracking Hover
        'button-tracking-hover-neutral': '#FAFAFA',
        'button-tracking-hover-black': '#525252',
        'button-tracking-hover-primary': '#4760B0',
        'button-tracking-hover-primary-tonal': '#A9B6DE',
        'button-tracking-hover-secondary': '#FFD14F',
        'button-tracking-hover-secondary-tonal': '#FFECB7',
      },
    },
  },
  corePlugins: {
    aspectRatio: true,
  },
  plugins: [require('@tailwindcss/aspect-ratio')],
}
export default config
