name: liara-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Liara CLI
        run: npm i -g @liara/cli

      - name: Deploy
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ]; then
            liara deploy --api-token="$LIARA_TOKEN" --no-app-logs --debug
          elif [ ${{ github.ref }} == 'refs/heads/develop' ]; then
            liara deploy --api-token="$LIARA_TOKEN" --no-app-logs --debug
          elif [ ${{ github.ref }} == 'refs/heads/staging' ]; then
            liara deploy --api-token="$LIARA_TOKEN" --no-app-logs --debug
          fi
